---
# update the variable values below before running the ncp_prep role
BMC: false
cni_url: <cni_url>
ovs_url: <ovs_url>
kmod_ovs_url: <url_for_kmod-openvswitch.rpm>
uplink_port: <uplink_port>
ncp_image_url: <image_url>
ncp_yaml_url: <ncp_yaml_url>