---
# update the variable values below before running the ncp role
ncp_scc_yaml_url: <ncp_scc_yaml_url>
agent_yaml_url: <agent_yaml_url>
apiserver_host_ip: <host_ip>
nsx_manager_ip: <manager_ip>
# If use_cert is set to true, you can skip setting nsx user and password
nsx_api_user: <nsx_api_user>
nsx_api_password: <nsx_api_password>
ncp_rbac_yaml_url: <ncp_rbac_yaml_url>
use_cert: false
# Uncomment and set correct path for the following two lines if use_cert is set to true
# nsx_api_cert_file: <nsx_api_cert_path>
# nsx_api_private_key_file: <nsx_api_priv_path>
cluster_name: occl-one